version: '2'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GITHUB_CLIENT_ID=A-GITHUB-CLIENT-ID
      - GITHUB_CLIENT_SECRET=A-GITHUB-CLIENT-SECRET
      - GITHUB_HOSTNAME=github.com (optional, used for GitHub Enterprise custom domains)
      - CALLBACK_URL=https://url-to-app/auth/callback
      - REPOSITORIES=org/repo,org/repo...
